apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "sumuthakscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "sumuthakscluster"
    spec:
      containers:
        - name: "sumuthakscluster"
          image: "sumuthacr.azurecr.io/sumuthakscluster"
          ports:
          - containerPort: 8000